[package]
name = "jrny"
version = "1.2.0"
authors = ["kevlarr <echo1@dvnl.net>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
chrono = "0.4.19"
log = "0.4.11"
postgres = { version = "0.17.1", features = ["with-chrono-0_4"] }
serde = { version = "1.0.104", features = ["derive"] }
sha2 = "0.9.2"
termcolor = "1.1.2"
toml = "0.5.6"
unicode-segmentation = "1.7.1"
