executor = "postgres"

# A more resilient strategy will be simply specifying a strategy
# to locate credentials, rather than including them here
[database]
host = "localhost"
port = 5432
name = "jrny_test"
user = "jrny_role"
